-- Emergency manual reference for recurring bookkeeping tables.
-- Normal releases use Flyway migrations from backend/src/main/resources/db/migration.

CREATE TABLE IF NOT EXISTS recurring_rules (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  user_id BIGINT NOT NULL,
  name VARCHAR(64) NOT NULL,
  type VARCHAR(16) NOT NULL,
  item_name VARCHAR(64) NOT NULL,
  amount DECIMAL(12,2) NOT NULL,
  channel VARCHAR(16) NOT NULL,
  online_app VARCHAR(64) NULL,
  offline_place VARCHAR(128) NULL,
  payment_method_id BIGINT NOT NULL,
  payment_method_name VARCHAR(64) NOT NULL,
  category_id BIGINT NOT NULL,
  category_name VARCHAR(64) NOT NULL,
  note VARCHAR(255) NULL,
  schedule_type VARCHAR(16) NOT NULL,
  interval_value INT NOT NULL DEFAULT 1,
  day_of_month INT NULL,
  weekday VARCHAR(16) NULL,
  start_date DATE NOT NULL,
  next_run_date DATE NULL,
  end_date DATE NULL,
  reminder_days_before INT NOT NULL DEFAULT 0,
  status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
  deleted TINYINT(1) NOT NULL DEFAULT 0,
  active_name VARCHAR(64) GENERATED ALWAYS AS (CASE WHEN deleted = 0 THEN name ELSE NULL END) STORED,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_recurring_rules_user_active_name (user_id, active_name),
  INDEX idx_recurring_rules_user_status_next (user_id, status, next_run_date, deleted),
  INDEX idx_recurring_rules_user_schedule (user_id, schedule_type, deleted),
  CONSTRAINT fk_recurring_rules_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_recurring_rules_category FOREIGN KEY (category_id) REFERENCES categories(id),
  CONSTRAINT fk_recurring_rules_payment_method FOREIGN KEY (payment_method_id) REFERENCES payment_methods(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS recurring_rule_runs (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  user_id BIGINT NOT NULL,
  rule_id BIGINT NOT NULL,
  rule_name VARCHAR(64) NOT NULL,
  due_date DATE NOT NULL,
  reminder_days_before INT NOT NULL DEFAULT 0,
  type VARCHAR(16) NOT NULL,
  item_name VARCHAR(64) NOT NULL,
  amount DECIMAL(12,2) NOT NULL,
  channel VARCHAR(16) NOT NULL,
  online_app VARCHAR(64) NULL,
  offline_place VARCHAR(128) NULL,
  payment_method_id BIGINT NOT NULL,
  category_id BIGINT NOT NULL,
  note VARCHAR(255) NULL,
  status VARCHAR(16) NOT NULL,
  transaction_id BIGINT NULL,
  error_message VARCHAR(255) NULL,
  processed_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_recurring_rule_runs_rule_due_date (rule_id, due_date),
  INDEX idx_recurring_rule_runs_user_status_due (user_id, status, due_date),
  INDEX idx_recurring_rule_runs_user_rule (user_id, rule_id, due_date),
  INDEX idx_recurring_rule_runs_transaction (transaction_id),
  CONSTRAINT fk_recurring_rule_runs_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_recurring_rule_runs_rule FOREIGN KEY (rule_id) REFERENCES recurring_rules(id) ON DELETE CASCADE,
  CONSTRAINT fk_recurring_rule_runs_category FOREIGN KEY (category_id) REFERENCES categories(id),
  CONSTRAINT fk_recurring_rule_runs_payment_method FOREIGN KEY (payment_method_id) REFERENCES payment_methods(id),
  CONSTRAINT fk_recurring_rule_runs_transaction FOREIGN KEY (transaction_id) REFERENCES transactions(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
